# Which plots to make. The options are: 
# --- 'nhi' = Column density map for a full cube (about 20 sq degrees)
# --- 'nhi_zoom' = Column density map zoom in, size is defined below by 'zoom_size'
# --- 'velocity' = 1st moment velocity map
# --- 'velocity_zoom' = Zoom in of the velocity map
# --- 'dispersion' = 2nd moment velocity dispersion map
# --- 'dispersion_zoom' = Zoom in of the dispersion map
# --- 'spectrum' = extracted 1D spectrum at the given coordinate
plots_to_make: ['nhi', 'velocity', 'nhi_zoom', 'velocity_zoom', 'dispersion', 'dispersion_zoom', 'spectrum', 'spectrum_zoom']


# Directory containing the data cubes
data_dir: '/hi4pi/'


# Directory to save the plots. Default is the current directory
save_dir: ''


# Output and save the spectrum?
save_spectrum: True


# Dispersion map type. Options are 'sigma' or 'fwhm'
dispersion_type: 'sigma'


# Colormaps to use for each plot. 
# Options can be found here: https://matplotlib.org/stable/gallery/color/colormap_reference.html
cm_nhi: 'viridis'
cm_nhi_zoom: 'viridis'
cm_velocity: 'coolwarm'
cm_velocity_zoom: 'coolwarm'
cm_dispersion: 'RdBu'
cm_dispersion_zoom: 'RdBu'


# Include a red 'x' for the target location
mark_target: True


# Plot gridlines
grid_nhi: True
grid_nhi_zoom: True
grid_velocity: True
grid_velocity_zoom: True
grid_dispersion: True
grid_dispersion_zoom: True
grid_spectrum: False
grid_spectrum_zoom: False
